Repository sjb-deck/deck, pull requests merged in 2023-07, with the labels that each got.

#33 Create add items and expiries
  __tests__/SearchBar.test.js
  __tests__/SearchFilter.test.js
  __tests__/components/AddItems/AddExpiryForm.test.js
  __tests__/components/AddItems/AddExpiryReview.test.js
  __tests__/components/AddItems/AddItemForm.test.js
  __tests__/components/AddItems/AddItemReview.test.js
  __tests__/components/AddItems/DateAndQuantity.test.js
  __tests__/components/AddItems/ErrorDialog.test.js
  __tests__/components/AddItems/ItemPotentialMatchDialog.test.js
  __tests__/components/AddItems/SuccessDialog.test.js
  __tests__/components/AddItems/TypeSelection.test.js
  __tests__/components/CartPopupModal/CartPopupModal.test.js
  __tests__/components/ItemContainer/ItemContainer.test.js
  __tests__/utils/submitForm.test.js
  components/AddItems/AddExpiryForm.js
  components/AddItems/AddExpiryReview.js
  components/AddItems/AddItemForm.js
  components/AddItems/AddItemReview.js
  components/AddItems/DateAndQuantity.js
  components/AddItems/ErrorDialog.js
  components/AddItems/ItemPotentialMatchDialog.js
  components/AddItems/SuccessDialog.js
  components/AddItems/TypeSelection.js
  components/SearchBar.js
  globals.js
  inventory/api_urls.py
  inventory/serializers.py
  inventory/src/js/addItem.js
  inventory/src/js/itemIndex.js
  inventory/templates/add_item.html
  inventory/urls.py
  inventory/views.py
  package-lock.json
  package.json
  requirements.txt
  utils/levenshteinDistance.js
  utils/submitForm.js
  webpack.config.js
Labels: feature

#34 Fix unable to click "enter" to submit form
  deck/src/js/login.js
Labels: bug

#44 New buttons for FA homepage
  components/NavBar/NavBar.js
  components/NavBar/NavDrawer.js
  globals.js
Labels: enhancement
